# Generated by Django 2.2.28 on 2023-08-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_swe23'),
    ]

    operations = [
        migrations.AddField(
            model_name='swe23',
            name='hfhdhdh',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
